<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Acorn.Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Konscious.Security.Cryptography.Argon2" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Acorn.Core.Tests" />
  </ItemGroup>

</Project>
